version: '3.8'  # Use the latest version that fits your needs

services:
  seq-dashboard:
    image: datalust/seq:latest
    container_name: seq-dashboard
    ports:
      - "5341:5341"
      - "18080:80"
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
      - seq_data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - 4317:4317
      - 55679:55679
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
        - ./otel-collector.yaml:/etc/otel-collector.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus.yaml

  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200:3200
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]

#  k6-tracing:
#    image: ghcr.io/grafana/xk6-client-tracing:v0.0.5
#    environment:
#      - ENDPOINT=otel-collector:4317
#    restart: always
#    depends_on:
#      - otel-collector

volumes:
  seq_data:
  tempo_data:
  grafana_data:
  prometheus_data: