version: '3.8'  # Use the latest version that fits your needs

services:
  seq-dashboard:
    image: datalust/seq:latest
    container_name: seq-dashboard
    ports:
      - "5341:5341"
      - "18080:80"
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
      - seq_data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - 4317:4317
      - 55679:55679

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    ports:
      - "3000:3000"

volumes:
  seq_data: